apiVersion: apps/v1
kind: Deployment
metadata:
  name: vote-app
  namespace: production
  annotations:
    pod.kubernetes.io/lifetime: 2m
  labels:
    app: vote-app
spec:
  selector:
    matchLabels:
      app: vote-app
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
  template:
    metadata:
      namespace: production
      labels:
        app: vote-app
    spec:
      containers:
      - name: vote-app
        image: {{GENIMAGE}}
        securityContext:
          allowPrivilegeEscalation: false
          capabilities:
            drop:
              - ALL
          runAsUser: 1000 
          runAsGroup: 1000 
          readOnlyRootFilesystem: true 
          runAsNonRoot: true
        imagePullPolicy: Always
        env:
            - name: PORT
              value: "80"
        ports:
        - containerPort: 80
        resources:
          requests:
            memory: "100Mi"
            cpu: "10m"
          limits:
            memory: "600Mi"
            cpu: "80m"

---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: vote-app
  name: vote-app
  namespace: production
spec:
  type: ClusterIP
  ports:
  - protocol: TCP
    name: http
    port: 80
    targetPort: 80
  selector:
    app: vote-app

---

apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  annotations:
    kubernetes.io/ingress.class: "nginx"
    nginx.ingress.kubernetes.io/force-ssl-redirect: "false"
  name: vote-ingress
  namespace: production
spec:
  tls:
  - hosts:
    - vote.henrysantiago.com
  rules:
  - host: vote.henrysantiago.com
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: vote-app
            port:
              number: 80