apiVersion: chaos-mesh.org/v1alpha1
kind: StressChaos
metadata:
  name: memory-stress-example
  namespace: production
spec:
  mode: all
  selector:
    labelSelectors:
      'app': 'vote-app'
  stressors:
    memory:
      workers: 4
      size: '570MB'
  duration: "120s"