apiVersion: v1
kind: Service
metadata:
  labels:
    app: worker-app
  name: worker-app
  namespace: production
spec:
  type: ClusterIP
  ports:
  - protocol: TCP
    name: http
    port: 80
    targetPort: 80
  selector:
    app: worker-app