name: Build and Deploy All Apps

on:
  push:
    branches:
      - 'main'
    paths:
      - 'result/**'
      - 'vote/**'
      - 'worker/**'
      - '.github/workflows/build-and-deploy-apps.yaml'

jobs:
  build-and-push-result:
    name: Build and Push Result App
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and Push Result Image
        uses: docker/build-push-action@v4
        with:
          context: ./result
          push: true
          tags: santiagososs/vote-result:latest

  build-and-push-vote:
    name: Build and Push Vote App
    runs-on: ubuntu-latest
    needs: build-and-push-result

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and Push Vote Image
        uses: docker/build-push-action@v4
        with:
          context: ./vote
          push: true
          tags: santiagososs/vote-app:latest

  build-and-push-worker:
    name: Build and Push Worker App
    runs-on: ubuntu-latest
    needs: build-and-push-vote

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and Push Worker Image
        uses: docker/build-push-action@v4
        with:
          context: ./worker
          push: true
          tags: santiagososs/worker-app:latest

  deploy:
    name: Deploy to AKS
    runs-on: ubuntu-latest
    needs: [build-and-push-worker, build-and-push-vote, build-and-push-result]

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Set up Azure CLI
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Get AKS Credentials
        run: az aks get-credentials --resource-group ${{ secrets.AKS_RG }} --name ${{ secrets.AKS_NAME }}

      - name: Apply Manifests
        run: kubectl apply -f manifests/ -n production -R
