name: Build, Scan and Deploy All Apps

on:
  push:
    branches:
      - 'main'
    paths:
      - 'result/**'
      - 'vote/**'
      - 'worker/**'
      - '.github/workflows/build-and-deploy-apps.yaml'
  workflow_dispatch:

jobs:
  build-and-push-result:
    name: Build and Push Result App
    runs-on: ubuntu-latest
 
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and Push Result Image
        uses: docker/build-push-action@v4
        with:
          context: ./result
          push: true
          tags: santiagososs/vote-result:${{ github.run_id }}

  build-and-push-vote:
    name: Build and Push Vote App
    runs-on: ubuntu-latest
    needs: build-and-push-result

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and Push Vote Image
        uses: docker/build-push-action@v4
        with:
          context: ./vote
          push: true
          tags: santiagososs/vote-app:${{ github.run_id }}

  build-and-push-worker:
    name: Build and Push Worker App
    runs-on: ubuntu-latest
    needs: build-and-push-vote

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and Push Worker Image
        uses: docker/build-push-action@v4
        with:
          context: ./worker
          push: true
          tags: santiagososs/worker-app:${{ github.run_id }}

  scan-images-sysdig-secure:
    name: Scan Images and Send Data
    runs-on: ubuntu-latest
    needs: [build-and-push-worker, build-and-push-vote, build-and-push-result]
    
    steps:  
        
    - name: Scanning Vote App Image
      run: |
        curl -LO "https://download.sysdig.com/scanning/bin/sysdig-cli-scanner/$(curl -L -s https://download.sysdig.com/scanning/sysdig-cli-scanner/latest_version.txt)/linux/amd64/sysdig-cli-scanner"
        chmod +x ./sysdig-cli-scanner
        SECURE_API_TOKEN=${{ secrets.sysdig_token }} ./sysdig-cli-scanner --apiurl ${{secrets.sysdig_endpoint}} santiagososs/vote-app:${{ github.run_id }}

    - name: Scanning Result App Image
      run: |
        curl -LO "https://download.sysdig.com/scanning/bin/sysdig-cli-scanner/$(curl -L -s https://download.sysdig.com/scanning/sysdig-cli-scanner/latest_version.txt)/linux/amd64/sysdig-cli-scanner"
        chmod +x ./sysdig-cli-scanner
        SECURE_API_TOKEN=${{ secrets.sysdig_token }} ./sysdig-cli-scanner --apiurl ${{secrets.sysdig_endpoint}} santiagososs/vote-result:${{ github.run_id }}
    
    - name: Scanning Worker App Image
      run: |
        curl -LO "https://download.sysdig.com/scanning/bin/sysdig-cli-scanner/$(curl -L -s https://download.sysdig.com/scanning/sysdig-cli-scanner/latest_version.txt)/linux/amd64/sysdig-cli-scanner"
        chmod +x ./sysdig-cli-scanner
        SECURE_API_TOKEN=${{ secrets.sysdig_token }} ./sysdig-cli-scanner --apiurl ${{secrets.sysdig_endpoint}} santiagososs/worker-app:${{ github.run_id }}

  deploy:
     name: Deploy to AKS
     runs-on: ubuntu-latest
     needs: scan-images-sysdig-secure

     steps:
       - name: Checkout Code
         uses: actions/checkout@v3

       - name: Update Image Tags in Manifests
         run: |
           sed -i "s!{{GENIMAGE}}!santiagososs/vote-result:${{ github.run_id }}!g" manifests/result/*.yaml
           sed -i "s!{{GENIMAGE}}!santiagososs/vote-app:${{ github.run_id }}!g" manifests/vote/*.yaml
           sed -i "s!{{GENIMAGE}}!santiagososs/worker-app:${{ github.run_id }}!g" manifests/worker/*.yaml

       - name: Commit and push changes to GitOps repo
         run: |
            git config --global user.name "github-actions[bot]"
            git config --global user.email "41898282+github-actions[bot]@users.noreply.github.com"
            git add manifests/
            git commit -m "chore(gitops): update image tag for deployment"
            git push
